<div class="posts-content">
<h2 class="greetings">Привет, <?= htmlspecialchars($login) ?>!</h2>
    <?php if (!empty($posts)): ?>
        <?php foreach ($posts as $post): ?>
            <div class="card">
                <a class="card-title" href="?page=post&id=<?= htmlspecialchars($post['id']); ?>">
                    Пост №<?= htmlspecialchars($post['id']) ?>
                </a>
                <!-- Миниатюра изображения -->
                <?php if (!empty($post['image'])): ?>
                    <div class="post-thumbnail">
                        <img src="uploads/posts/<?= urlencode($post['image']) ?>"
                        alt="Миниатюра к посту"
                        class="img-thumbnail" >
                    </div>
                <?php endif; ?>
                <!-- Заголовок поста -->
                <p class="card-title"><?= htmlspecialchars($post['title']) ?? '' ?></p>

                <!-- Категория -->
                <?php if (!empty($categories)) : ?>
                    <?php foreach ($categories as $key => $category) : ?>
                        <?php if ($key === $post['category_id']) : ?>
                            <p class="card-category">
                                <?= $category; ?>
                            </p>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>

                <!--Текст поста -->
                <p class="card-text"><?= htmlspecialchars($post['text']) ?? '' ?></p>
            <div class="edit-delete-likes-forms">
                <!-- Кнопка «Редактировать» -->
                <form class="edit-form" action="<?= BASE_URL ?>" method="GET">
                    <input type="hidden" name="page" value="editAdmin">
                    <input type="hidden" name="id" value="<?= htmlspecialchars($post['id']) ?>">
                    <button type="submit" class="btn-edit">Редактировать</button>
                </form>

                <!-- Кнопка «Удалить» с подтверждением -->
                <form class="delete-form" action="<?= BASE_URL ?>" method="GET"
                    onsubmit="return confirm('Удалить пост?')">
                    <input type="hidden" name="page" value="deleteAdmin">
                    <input type="hidden" name="id" value="<?= htmlspecialchars($post['id']) ?>">
                    <button type="submit" class="btn-delete">Удалить</button>
                </form>
            </div>

            <!-- комментарии -->
            <div class="comments">
                <?php foreach($comments as $comment) :
                    if ($comment['post_id'] === $post['id']) : ?>
                        <p class="comment comment-admin"><?= htmlspecialchars( $comment['content'])?></p>
                        <p class="comment comment-author comment-author-admin"><?= htmlspecialchars( $comment['author'])?></p>
                        <p class="comment comment-date comment-date-admin"><?= htmlspecialchars( $comment['date'])?></p>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
    </div>
        <?php endforeach; ?>
    <?php else: ?>
        <!-- Если постов нет — выводим сообщение -->
        <p>Нет постов для отображения</p>
    <?php endif; ?>
</div>









